name: Build iOS
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-ios:
    needs: install-and-test
    runs-on: macOS-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Dump file hirearchy
        run: ls -R
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Build archive
	run: |
	  xcodebuild -sdk iphoneos -project testing_project/testing_project.xcodeproj \
	    -configuration Release -scheme testing_project \
            -derivedDataPath DerivedData \
            -archivePath DerivedData/Archive/testing_project archive
      - name: Export Archive
        run: |
          xcodebuild -exportArchive \
            -archivePath DerivedData/Archive/testing_project.xcarchive \
            -exportPat DerivedData/ipa 
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: testing_project.ipa
          path: ios/build/
